In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\sowmy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np 

In [4]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [8]:
a.size

5

In [9]:
a.shape

(5,)

In [10]:
a.ndim

1

In [11]:
mean = a.mean()
mean

np.float64(2.0)

In [12]:
standard_deviation=a.std()
standard_deviation

np.float64(1.4142135623730951)

In [13]:
max_b = a.max()
max_b

np.int64(4)

In [14]:
# Create a list

arr = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
arr

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [15]:
A = np.array(arr)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [17]:
A.ndim


2

In [18]:
A.shape
A.size
A.dtype

dtype('int64')

In [19]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 
Z= X+Y
Z

array([[3, 1],
       [1, 3]])